# Copyright (c) 2023 - now Shuaiwen Cui
# Built upon MkDocs & Material for MkDocs

# Project information
site_name: Eureka!
site_url: https://localhost:8000/ # build and run on server, to visit it, type in the server's IP address and port number like this: xxx.xxx.xxx.xxx:8000
site_author: Shuaiwen Cui
site_description: >-
  Welcome to Shaun's rabbit hole. This site serves as a personal knowledge base for me to record my thoughts and ideas. It is also a place for me to share my knowledge and experience with the world. I hope you find something useful here.

# Repository
repo_name: Shuaiwen-Cui/Infinity
repo_url: https://github.com/Shuaiwen-Cui/Infinity.git/

# Copyright
copyright: Copyright &copy; 2023 ~ now | 🚀 Shuaiwen Cui (Shaun)

# Configuration
theme:
  custom_dir: material/overrides
  name: material
  logo: static/images/logo.png
  language: en
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.code.select
    # - content.tabs.link
    - content.tooltips
    # - header.autohide
    # - navigation.expand # expand the side navigation bar by default
    - navigation.footer
    - navigation.indexes # documents can be directly attached to sections, which is particularly useful for providing overview pages
    # - navigation.instant
    - navigation.instant.prefetch # for large file
    - navigation.instant.progress # loading progress bar
    - navigation.path # breadcrumb path on top of page
    # - navigation.prune # only build the visible part of the navigation tree
    - navigation.sections # navigation - top level will render as sections
    - navigation.tabs
    - navigation.tabs.sticky # tabs stick to the top of the page
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate # toc is merged into the left navigation bar
  palette:
    - media: "(prefers-color-scheme)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference
  font:
    text: Roboto
    code: Roboto Mono
  favicon: static/images/logo.png
  icon:
    logo: logo
    previous: fontawesome/solid/angle-left
    next: fontawesome/solid/angle-right
    tag:
      default-tag: fontawesome/solid/tag
      hardware-tag: fontawesome/solid/microchip
      software-tag: fontawesome/solid/laptop-code

# Plugins
plugins:
  - tags
  - blog
  - rss:
      match_path: blog/posts/.* 
      date_from_meta:
        as_creation: date
      categories:
        - categories
        - tags 
  # - social
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - minify:
      minify_html: true
  # - privacy
  - i18n:
      docs_structure: suffix
      fallback_to_default: true
      reconfigure_material: true
      reconfigure_search: true
      languages:
        - locale: en
          default: true
          name: English
          build: true
          # site_name: Infinity
        - locale: zh
          name: 简体中文
          build: true
          nav_translations: # note that all titles and subtitles in the navigation bar that need to be translated can be put here, but with no indentation
            HOME: 首页
            ABOUT: 关于
            SPONSORSHIP: 赞助
            MATH: 数学
            GEOMETRY-GRAPHICS: 几何与图形学
            COMPUTER-GRAPHICS-FROM-SCRATCH: 计算机图形学从零开始
            CS: 计算机科学
            OS: 操作系统
            DATA-BASE: 数据库
            CODING: 编程
            C/C++: C/C++
            C: C
            C-NOTES: C笔记
            C++: C++
            C++-NOTES: C++笔记
            PYTHON: Python
            ROADMAP: 路线图
            HTML/CSS/JS: HTML/CSS/JS
            HTML: 超文本标记语言
            CSS: 级联样式表
            JAVASCRIPT: JAVASCRIPT
            EMBEDDED-SYS: 嵌入式系统
            THEORY: 理论
            ELECTRONICS: 电子学
            CIRCUITS: 电路
            FREERTOS: 实时操作系统
            LINUX: LINUX
            SIMULATION: 仿真
            DEVKIT: 开发板
            ARDUINO: ARDUINO
            STM32: STM32
            ESP32: ESP32
            RASPBERRYPI: 树莓派
            JETSON: JETSON
            IDE: 集成开发环境
            KEIL: KEIL
            OFFICIAL-GUIDE-MDK4: MDK4官方指南
            OFFICIAL-GUIDE-MDK5: MDK5官方指南
            PREFACE: 前言
            MDK-INTRODUCTION: MDK简介
            CMSIS: CMSIS库
            SOFTWARE-COMPONENTS: 软件组件
            CREATE-APP: 创建应用
            DEBUG-APP: 调试应用
            MDK-MIDDLEWARE: MDK中间件
            PLATFORMIO: PLATFORMIO
            DSP: 数字信号处理
            NOTE-DSP-STUFF: “DSP相关内容”笔记
            TIME-FREQ-ANA: 时频分析
            PERCEPTION: 感知
            CONTROL: 控制
            ACTUATION: 执行
            ROS: 机器人操作系统
            OFFICIAL-GUIDE: 官方指南
            INSTALLATION: 安装
            DISTRIBUTION: 发行版
            TUTORIALS: 教程
            CLI-TOOLS: 命令行工具
            HANDSON-ROS: 动手学ROS
            P1-GET-STARTED: P1-入门
            VISUALIZATION: 可视化    
            WEB-BASED: WEB端
            CLIENT-BASED: 客户端        
            IOT: 物联网
            WSN: 无线传感器网络
            MQTT: 消息队列遥测传输协议
            BROKER: 代理
            CLIENT: 客户端
            CLOUD: 云
            CLOUD-TECH: 云技术
            HANDS-ON: 上手实践
            Have A Server: 拥有一台服务器
            Server Configuration: 服务器配置
            Get A Domain Name: 获得一个域名
            AI: 人工智能
            BASICS: 基础
            FRAMEWORKS: 框架
            MLP: 多层感知机
            CNN: 卷积神经网络
            RNN: 循环神经网络
            TRANSFORMER: “变形金刚”
            GAN: 生成对抗网络
            RL: 强化学习
            FL: 联邦学习
            CV: 计算机视觉
            NOTE-D2L: 动手学深度学习
            CH1-INTRO: CH1-引言
            CH2-PRE: CH2-预备知识
            CH3-LNN: CH3-线性神经网络
            SHM: 结构健康监测
            DEV: 开发
            DEVENV: 开发环境
            LATEX: LATEX
            REMOTE-CONTROL: 远程控制
            CLOUD-SYNC: 云同步
            FRONT-END: 前端
            BACK-END: 后端
            RESEARCH: 研究
            PROJECT: 项目
            TECH-BLOG: 技术博客
# # Hooks
# hooks:
#   - material/overrides/hooks/shortcodes.py
#   - material/overrides/hooks/translations.py

# Additional configuration
extra:
  generator: false
  status:
    new: Recently added
    deprecated: Deprecated
  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/thumb-up-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/thumb-down-outline
          name: This page could be improved
          data: 0
          note: >- 
            Thanks for your feedback! Help us improve this page by
            using our <a href="..." target="_blank" rel="noopener">feedback form</a>.
  # alternate:
  #   - name: English
  #     link: /en/ 
  #     lang: en
  #   - name: Chinese
  #     link: /zh/
  #     lang: zh
  social:
    - icon: fontawesome/solid/house
      link: http://www.cuishuaiwen.com/
    - icon: fontawesome/brands/github
      link: https://github.com/Shuaiwen-Cui
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/shaun-shuaiwen-cui/
    - icon: fontawesome/brands/researchgate
      link: https://www.researchgate.net/profile/Shuaiwen-Cui
    - icon: fontawesome/brands/orcid
      link: https://orcid.org/0000-0003-4447-6687
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/ShuaiwenC
  tags:
    Default: default-tag
    Hardware: hardware-tag
    Software: software-tag
  # consent:
  #   title: Cookie consent
  #   description: >- 
  #     We use cookies to recognize your repeated visits and preferences, as well
  #     as to measure the effectiveness of our documentation and whether users
  #     find what they're searching for. With your consent, you're helping us to
  #     make our documentation better.

# Extra Configuration 
extra_javascript:
  # - https://giscus.app/client.js
  - /CODING/PYTHON/Book1_Python-For-Beginners_编程不难.pdf
  # - javascripts/katex.js 
  # - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.js  
  # - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/contrib/auto-render.min.js
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - javascripts/embed-pdf.js

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      normalize_issue_symbols: true
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      auto_append:
        - includes/mkdocs.md
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Page Navigation Tree
nav:
  - HOME: 
      - "index.md"
      - ABOUT: "./HOME/about.md"
      - SPONSORSHIP: "./HOME/sponsorship.md"
  - MATH:
      - "./MATH/math.md"
      - GEOMETRY-GRAPHICS: 
          - COMPUTER-GRAPHICS-FROM-SCRATCH: "./MATH/GEOMETRY-GRAPHICS/COMPUTER-GRAPHICS/computer-graphics.md"
  - CS: 
      - "./CS/CS.md"
      - OS: "./CS/OS/os.md"
      - DATA-BASE: "./CS/DATA-BASE/data-base.md"
  - CODING: 
      - "./CODING/coding.md"
      - C/C++:
          # - "./C-C++/c-c++.md"
          - C: "./CODING/C-C++/C/c.md"
          - C-NOTES: "./CODING/C-C++/C-NOTES/c-notes.md" 
          - C++: "./CODING/C-C++/C++/c++.md"
          - C++-NOTES: 
              - "./CODING/C-C++/C++-NOTES/c++-notes.md"
              - CH01: "./CODING/C-C++/C++-NOTES/CH01/ch01.md"
      - PYTHON: 
          - "./CODING/PYTHON/python.md"
          - ROADMAP: "./CODING/PYTHON/ROADMAP/roadmap.md"
      - HTML/CSS/JS: 
          - HTML: "./CODING/HTML-CSS-JS/HTML/html.md"
          - CSS: "./CODING/HTML-CSS-JS/CSS/css.md"
          - JAVASCRIPT: "./CODING/HTML-CSS-JS/JS/js.md"
  - EMBEDDED-SYS: 
      - "./EMBEDDED-SYS/embedded-sys.md"
      - THEORY:
          - ELECTRONICS: "./EMBEDDED-SYS/THEORY/ELECTRONICS/electronics.md"
          - CIRCUITS: "./EMBEDDED-SYS/THEORY/CIRCUITS/circuits.md"
          - FREERTOS: "./EMBEDDED-SYS/THEORY/FREERTOS/freertos.md"
          - LINUX: "./EMBEDDED-SYS/THEORY/LINUX/linux.md"
      - SIMULATION: 
          - "./EMBEDDED-SYS/SIMULATION/simulation.md"
          - RENODE: 
              - "./EMBEDDED-SYS/SIMULATION/RENODE/renode.md"
          - WOKWI: 
              - "./EMBEDDED-SYS/SIMULATION/WOKWI/wokwi.md"
      - DEVKIT: 
          - ARDUINO: "./EMBEDDED-SYS/DEVKIT/ARDUINO/arduino.md"
          - STM32: "./EMBEDDED-SYS/DEVKIT/STM32/stm32.md"
          - ESP32: "./EMBEDDED-SYS/DEVKIT/ESP32/esp32.md"
          - RASPBERRYPI: "./EMBEDDED-SYS/DEVKIT/RASPBERRYPI/raspberrypi.md"
          - JETSON: "./EMBEDDED-SYS/DEVKIT/JETSON/jetson.md"
      - IDE: 
          - "./EMBEDDED-SYS/IDE/ide.md"
          - KEIL: 
              - "./EMBEDDED-SYS/IDE/KEIL/keil.md"
              - OFFICIAL-GUIDE-MDK4: 
                  - "EMBEDDED-SYS/IDE/KEIL/GUIDE-MDK4/guide-mdk4.md"
              - OFFICIAL-GUIDE-MDK5: 
                  - PREFACE: "./EMBEDDED-SYS/IDE/KEIL/GUIDE-MDK5/PREFACE/preface.md"
                  - MDK-INTRODUCTION: "./EMBEDDED-SYS/IDE/KEIL/GUIDE-MDK5/MDK-INTRODUCTION/mdk-introduction.md"
                  - CMSIS: "./EMBEDDED-SYS/IDE/KEIL/GUIDE-MDK5/CMSIS/cmsis.md"
                  - SOFTWARE-COMPONENTS: "./EMBEDDED-SYS/IDE/KEIL/GUIDE-MDK5/SOFTWARE-COMPONENTS/software-components.md"
                  - CREATE-APP: "./EMBEDDED-SYS/IDE/KEIL/GUIDE-MDK5/CREATE-APP/create-app.md"
                  - DEBUG-APP: "./EMBEDDED-SYS/IDE/KEIL/GUIDE-MDK5/DEBUG-APP/debug-app.md"
                  - MDK-MIDDLEWARE: "./EMBEDDED-SYS/IDE/KEIL/GUIDE-MDK5/MDK-MIDDLEWARE/mdk-middleware.md"
          - PLATFORMIO: "./EMBEDDED-SYS/IDE/PLATFORMIO/platformio.md"

  - DSP: 
      - "./DSP/dsp.md"
      - NOTE-DSP-STUFF:
          - TIME-FREQ-ANA:
              - CH01: "./DSP/NOTE-DSP-STUFF/TIME-FREQ-ANA/CH01/tf-ana-ch01.md"
              - CH02: "./DSP/NOTE-DSP-STUFF/TIME-FREQ-ANA/CH02/tf-ana-ch02.md"
              - CH03: "./DSP/NOTE-DSP-STUFF/TIME-FREQ-ANA/CH03/tf-ana-ch03.md"
              - CH04: "./DSP/NOTE-DSP-STUFF/TIME-FREQ-ANA/CH04/tf-ana-ch04.md"
              - CH05: "./DSP/NOTE-DSP-STUFF/TIME-FREQ-ANA/CH05/tf-ana-ch05.md"
              - CH06: "./DSP/NOTE-DSP-STUFF/TIME-FREQ-ANA/CH06/tf-ana-ch06.md"
              - CH07: "./DSP/NOTE-DSP-STUFF/TIME-FREQ-ANA/CH07/tf-ana-ch07.md"
              - CH08: "./DSP/NOTE-DSP-STUFF/TIME-FREQ-ANA/CH08/tf-ana-ch08.md"
              - CH09: "./DSP/NOTE-DSP-STUFF/TIME-FREQ-ANA/CH09/tf-ana-ch09.md"
              - CH10: "./DSP/NOTE-DSP-STUFF/TIME-FREQ-ANA/CH10/tf-ana-ch10.md"
  - PERCEPTION: 
      - "./PERCEPTION/perception.md"
  - CONTROL: 
      - "./CONTROL/control.md"
  - ACTUATION: 
      - "./ACTUATION/actuation.md"
      - ROS: 
          - "./ACTUATION/ROS/ros.md"
          - OFFICIAL-GUIDE:
              - INSTALLATION: "./ACTUATION/ROS/OFFICIAL-GUIDE/INSTALLATION/installation.md"
              - DISTRIBUTION: "./ACTUATION/ROS/OFFICIAL-GUIDE/DISTRIBUTION/distribution.md"
              - TUTORIALS: 
                  - CLI-TOOLS: "./ACTUATION/ROS/OFFICIAL-GUIDE/TUTORIALS/CLI-TOOLS/cli-tools.md"
                  
      - HANDSON-ROS: 
          - "./ACTUATION/HANDSON-ROS/handson-ros.md"
          - P1-GET-STARTED: "./ACTUATION/HANDSON-ROS/P1-GET-STARTED/p1-get-started.md"
  - IOT: 
      - "./IOT/iot.md"
      - WSN: 
          - "./IOT/WSN/wsn.md"
      - MQTT: 
          - "./IOT/MQTT/mqtt.md"
          - BROKER: "./IOT/MQTT/BROKER/broker.md"
          - CLIENT: "./IOT/MQTT/CLIENT/client.md"
  - CLOUD: 
      - "./CLOUD/cloud.md"
      - CLOUD-TECH: "./CLOUD/CLOUD-TECH/cloud-tech.md"
      - HANDS-ON:
          - Have A Server: "./CLOUD/HANDS-ON/001-HAVE-A-SERVER/have-a-server.md"
          - Server Configuration: "./CLOUD/HANDS-ON/002-SERVER-CONFIG/server-config.md"
          - Get A Domain Name: "./CLOUD/HANDS-ON/003-DOMAIN-NAME/domain-name.md"
  - AI: 
      # - "./AI/ai.md"
      - BASICS: "./AI/BASICS/basics.md"
      - FRAMEWORKS: "./AI/FRAMEWORKS/frameworks.md"
      - MLP: "./AI/MLP/mlp.md"
      - CNN: "./AI/CNN/cnn.md"
      - RNN: "./AI/RNN/rnn.md"
      - TRANSFORMER: "./AI/TRANSFORMER/transformer.md"
      - GAN: "./AI/GAN/gan.md"
      - RL: "./AI/RL/rl.md"
      - FL: "./AI/FL/fl.md"
      - CV: "./AI/CV/cv.md"
      - NOTE-D2L: 
          - CH1-INTRO: "./AI/NOTE-D2L/CH1-INTRO/ch1-intro.md"
          - CH2-PRE: "./AI/NOTE-D2L/CH2-PRE/ch2-pre.md"
          - CH3-LNN: "./AI/NOTE-D2L/CH3-LNN/ch3-lnn.md"
  - SHM: 
      - "./SHM/shm.md"
  - DEV: 
      # - "./DEV/dev.md"
      - DEVENV: 
          # - "./DEV/DEVENV/devenv.md"
          - LATEX: "./DEV/DEVENV/LATEX/latex.md"
          - REMOTE-CONTROL: "./DEV/DEVENV/REMOTE-CONTROL/remote-control.md"
          - CLOUD-SYNC: "./DEV/DEVENV/CLOUD-SYNC/cloud-sync.md"
      - FRONT-END: "./DEV/FRONT-END/front-end.md"
      - BACK-END: "./DEV/BACK-END/back-end.md"
      - VISUALIZATION:
          - WEB-BASED: "./DEV/VISUALIZATION/WEB-BASED/web-based.md"
          - CLIENT-BASED: "./DEV/VISUALIZATION/CLIENT-BASED/client-based.md"
  - RESEARCH: 
      - "./RESEARCH/research.md"
  - PROJECT: 
      - "./PROJECT/project.md"
      - TECH-BLOG: "./PROJECT/TECH-BLOG/mkdocs_and_material.md"
    
# if there are sub nodes under a node, then there should not be a link right after the node. All the stuff should be placed under the node.

# example

# [incorrect use]
# - CLOUD: "./CLOUD/cloud.md"
#     - CLOUD-TECH: "./CLOUD/CLOUD-TECH/cloud-tech.md"

# [correct use]
# - CLOUD: 
#     - "./CLOUD/cloud.md"
#     - CLOUD-TECH: "./CLOUD/CLOUD-TECH/cloud-tech.md"